### ISSUE TITLE
UI Design osm verify and upload

### ISSUE THREAD

**Issue by ukanga** [onaio/omk-push#5]
New site
1. User did data collection using OpenMapKit and ODK Collect. Data is on Ona. Want to push to OpenStreetMap.
2. Using same username/login as Ona, login to site.
3. In the site, forced to login to OSM (can't do anything unless done)
4. See a list of forms with OSM data organized by project (all of them, no metadata lookup yet)
5. Go to a form. See list of submissions within that form with OSM data: Table - submission ID + OSM columns. Diff tags (mayyybe). Map - all the points. 
6. Email-style checkbox and toggle all in order to "Submit to OSM"
7. Click a submission - should highlight that one on map. And vice versa. (Not sure if this is related to toggle).
8. In the list, hide everything without OSM data and that has already been submitted (metadata for this is stored in Ona).

**Comment by rowo** [comment]
@ukanga here's my clickable wires: https://docs.google.com/a/ona.io/file/d/0B3wlsuQEG5hydTNoZnFlUy1oZ0U/edit

Images below. Let me know if anything doesn't make sense.

![home](https://cloud.githubusercontent.com/assets/1584163/7306214/86a8d536-e9d1-11e4-856e-f44fcc1432be.png)

![form](https://cloud.githubusercontent.com/assets/1584163/7306216/912e0aa8-e9d1-11e4-8a93-58babc1564b5.png)

**Comment by rowo** [comment]
@ukanga I'm closing this. How's this going?
